### ISSUE TITLE
Naming issues

### ISSUE THREAD

**Issue by GiggleLiu** [QuantumBFS/YaoBase.jl#3]
A list of naming issues to keep track

- [x] `increase(reg, ...)` is too general, one can hardly get what it is for.
- [x] `setto!(reg, ...)` has the confusion that we set the register state to another state, maybe `collapseto!` is a better name if the target state has to be a product state.

updating...

**Comment by Roger-luo** [comment]
I like `collapseto!` This is more accurate neither setto nor reset reveals what this function really does.

**Comment by Roger-luo** [comment]
# Choose one

The following variable names are used for the same meaning everywhere... it's a bit confusing even for myself. choose one.

- [x] `locations/locs`, `ibits`, `address/addrs`: the location/address of a quantum circuit wire, starts from `1` as Julian indices.
- [x] `bit_config`, `bits`, `config`, `val`: the binary configuration of a qubit, e.g 010101

`locations`/`locs` might be better, so we could use a shorter name `bits` for configurations while staying distinguishable. 

The control locations and control bits will then make more sense as what's documentation describes.

# Keywords name conventions

- [x] `nbit` -> `to_nactive`  in `relax`/`focus`, `to_nactive` looks more legible since the total number of qubits is not actually changed after `relax!`/`focus!` is called.
- [x] `val` -> one of the above name (I'm temporarily using `bit_config`, but prefers `bits`), we need to make sure no `ibits` if we start using `bits` for this. `bits` is the original word for `010101` configurations.

**Comment by GiggleLiu** [comment]
1. `locs`, `clocs` for control bits, `loc` for single qubit.
2. `config`
3. agree, but isn't this keyword appears only in `relax!`?

**Comment by Roger-luo** [comment]
not sure, there are some `nbit` keywords in Blocks as well. But let's keep this in mind, use `to_nactive` for all possible keywords.

**Comment by GiggleLiu** [comment]
`nbit` is ok for blocks, since only for registers, `active` makes sense.

**Comment by Roger-luo** [comment]
@GiggleLiu double check, anything else to tweak in this package? I'm going to port this to Yao.jl.

**Comment by GiggleLiu** [comment]
Great job! I do find some issues to be resolved

* [x] `@interface select(register::AbstractRegister, bits...) = select!(copy(register), bits...)` is not efficient.
It doubles the memory cost, the original `select` is much more efficient.

A proper interface of `select!` should be `select!(target_reg, source_reg, bits...)`.

* [x] keyword `ntimes` should be rollback to `nshot`, this is a widely used terminology.

* [x] Here, the depwarn is not correct. And the compatibility with respect to keywork arguments should also be fixed.

```julia
julia> measure_reset!(reg, val=0)
┌ Warning: `measure_reset!(r::AbstractRegister; val::Int=0)` is deprecated, use `measure_collapseto!(r; bit_config=val)` instead.
│   caller = ip:0x0
└ @ Core :-1
ERROR: MethodError: no method matching measure_collapseto!(::ArrayReg{1,Complex{Float64},Array{Complex{Float64},2}}; bit_config=0)
```

* [x] `measure_remove!` with `locs` is removed by accident?
